/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FiemsConectaPrivacidadeRouteImport } from './routes/fiems-conecta-privacidade'
import { Route as IndexRouteImport } from './routes/index'

const FiemsConectaPrivacidadeRoute = FiemsConectaPrivacidadeRouteImport.update({
  id: '/fiems-conecta-privacidade',
  path: '/fiems-conecta-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fiems-conecta-privacidade': typeof FiemsConectaPrivacidadeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fiems-conecta-privacidade': typeof FiemsConectaPrivacidadeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fiems-conecta-privacidade': typeof FiemsConectaPrivacidadeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fiems-conecta-privacidade'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fiems-conecta-privacidade'
  id: '__root__' | '/' | '/fiems-conecta-privacidade'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FiemsConectaPrivacidadeRoute: typeof FiemsConectaPrivacidadeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/fiems-conecta-privacidade': {
      id: '/fiems-conecta-privacidade'
      path: '/fiems-conecta-privacidade'
      fullPath: '/fiems-conecta-privacidade'
      preLoaderRoute: typeof FiemsConectaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FiemsConectaPrivacidadeRoute: FiemsConectaPrivacidadeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
